# Generated by Django 4.1 on 2022-08-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_complated',
            new_name='is_completed',
        ),
    ]
